name: Tip Report
description: 다른 사람이 써야할 것 같은 코드 설명해주는 리포트입니다.
title: "[Tip] "
body:
  - type: markdown
    attributes:
      value: |
        다른 사람들과 공유해야 하는 것들을 적어주세요!
  - type: textarea
    id: new-feature
    attributes:
      label: 공유할 내용
      description: 다른 사람들에게 알려줄 내용을 적어주세요
      placeholder: ex ) 상단바 activity에 추가하는 방법
    validations:
      required: true
  - type: textarea
    id: todo
    attributes:
      label: Read
      description: 다른 사람들 읽고 체크해주세요
      value: |
        - [ ] 김수현
        - [ ] 박기연
        - [ ] 박현주
        - [ ] 허나영
